version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "area/ci"
      - "kind/update"
      - "priority/low"

  - package-ecosystem: "docker"
    directory: /
    schedule:
      interval: "weekly"
    labels:
      - "area/ci"
      - "kind/update"
      - "priority/medium"
