name: Bug Report
description: Submit a bug report to help us improve
title: 'bug report: '
labels:
  - kind/bug/report
  - meta/needs triage

body:
  - type: checkboxes
    id: preliminary-checks
    attributes:
      label: 📝 Preliminary Checks
      description: |
        By submitting this issue, you agree to our [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md).
      options:
        - label: I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: 👀 What Happened?
      description: How did this differ from your expectations?
      placeholder: Although `LOG_LEVEL=debug` is set, the logs are missing debug output.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 👟 Reproduction Steps
      description: |
        How did you trigger this bug? Please walk us through it step by step.
        Please use [fenced code blocks](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks) when pasting lots of text!
      placeholder: The easier it is for us to reproduce your issue, the sooner we can help resolve it 😉
  - type: input
    id: mailserver-version
    attributes:
      label: 🐋 DMS Version
      description: On which version (image tag) did you encounter this bug?
      placeholder: v12.1.0 (do not put "latest")
    validations:
      required: true
  - type: input
    id: operating-system
    attributes:
      label: 💻 Operating System and Architecture
      description: |
        Which OS is your docker host running on?
        **NOTE:** Windows and macOS have limited support.
      placeholder: Debian 11 (Bullseye) x86_64, Fedora 38 ARM64
    validations:
      required: true
  - type: textarea
    id: container-configuration-files
    attributes:
      label: ⚙️ Container configuration files
      description: |
        Show us the `compose.yaml` file or command that you used to run DMS (and possibly other related services).
        - This field is formatted as YAML.
        - If you are using Kubernetes, you can alternatively share your manifest files here.
      render: yml
  - type: textarea
    id: relevant-log-output
    attributes:
      label: 📜 Relevant log output
      description: |
        Show us relevant log output here.
        - This field expects only plain text (_rendered as a fenced code block_).
        - You can enable debug output by setting the environment variable `LOG_LEVEL` to `debug` or `trace`.
      render: Text
