#!/bin/sh
VCS_REF=$(git rev-parse --short HEAD)
VCS_VERSION=$(git describe)

docker build \
	--build-arg VCS_REF="$VCS_REF" \
	--build-arg VCS_VERSION="$VCS_VERSION" \
	-f "$DOCKERFILE_PATH" -t "$IMAGE_NAME" .
