{{/* This whole template is only necessary if we're using rainloop */}}
{{ if .Values.rainloop.enabled -}}  
---
kind: "Service"
apiVersion: "v1"
metadata:
  annotations:
    ## These annontations mark the service as monitorable by Prometheus, both directly as a service level metric and
    ## via the blackbox exporter. For more information, see
    ## values.yaml
    prometheus.io/scrape: {{ .Values.monitoring.service.scrape | quote }}
    prometheus.io/probe: {{ .Values.monitoring.service.probe | quote }}
    prometheus.io/path: {{ .Values.monitoring.service.path | quote }}
    prometheus.io/port: {{ .Values.monitoring.service.port | quote }}
    ##  
    {{ if eq .Values.service.type "LoadBalancer" }}service.beta.kubernetes.io/external-traffic: "OnlyLocal"{{ end }}
  labels:
    app: {{ template "dockermailserver.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "dockermailserver.fullname" . }}-rainloop
spec:
  selector:
    app: {{ template "dockermailserver.fullname" . }}-rainloop
    release: "{{ .Release.Name }}"
  ports:
    - port: {{ .Values.rainloop.service.port }}
      targetPort: {{ .Values.rainloop.container.port }}
      protocol: TCP
      name: http
{{ end }}