name: 'Build, Test & Deploy'

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - target/**
      - .dockerignore
      - .gitmodules
      - Dockerfile
      - setup.sh
    tags:
      - '*.*.*'

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    name: 'Build AMD64 Image'
    uses: ./.github/workflows/generic_build.yml

  build-image-arm64:
    name: 'Build ARM64 Image'
    uses: ./.github/workflows/generic_build.yml
    with:
      platforms: linux/arm64
      runner: ubuntu-24.04-arm

  run-tests:
    name: 'Test AMD64 Image'
    needs: build-image
    uses: ./.github/workflows/generic_test.yml

  publish-images:
    name: 'Publish AMD64 and ARM64 Image'
    needs: [build-image, build-image-arm64, run-tests]
    uses: ./.github/workflows/generic_publish.yml
    secrets: inherit
