name: 'Deploy :edge on Schedule'

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 5

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  build-image-amd64:
    name: 'Build AMD64 Image'
    uses: ./.github/workflows/generic_build.yml

  build-image-arm64:
    name: 'Build ARM64 Image'
    uses: ./.github/workflows/generic_build.yml
    with:
      platforms: linux/arm64
      runner: ubuntu-24.04-arm

  scan-image:
    name: 'Scan Image for Vulnerabilities'
    needs: build-image-amd64
    uses: ./.github/workflows/generic_vulnerability-scan.yml

  publish-images:
    name: 'Publish Images'
    needs: [build-image-amd64, build-image-arm64]
    uses: ./.github/workflows/generic_publish.yml
    secrets: inherit
