name: "Test Merge Requests"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - target/**
      - test/**
      - .dockerignore
      - .gitmodules
      - Dockerfile
      - Makefile
      - setup.sh
      - .github/workflows/generic_build.yml
      - .github/workflows/generic_test.yml
      - .github/workflows/test_merge_requests.yml

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-image-amd64:
    name: "Build AMD64 Image"
    uses: ./.github/workflows/generic_build.yml

  run-tests:
    name: "Test AMD64 Image"
    needs: build-image-amd64
    uses: ./.github/workflows/generic_test.yml

  job-build-arm:
    name: "Build ARM64 Image"
    uses: ./.github/workflows/generic_build.yml
    with:
      platforms: linux/arm64
      runner: ubuntu-24.04-arm
